version: "3"

services:
  database:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=movie
      - MYSQL_ROOT_PASSWORD=hnam23012002
    ports:
      - "3307:3306"
    volumes:
      - $HOME/database:/var/lib/mysql
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
    # expose:
    networks:
      - movie_api_network

  backend:
    build: .
    restart: always
    container_name: movie_api
    environment:
      DB_DATABASE: movie
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: hnam23012002
      DB_DIALECT: mysql
      NODE_ENV: production

      # DB_DATABASE: bihdmoolq3mqdhd9qroc
      # DB_HOST: bihdmoolq3mqdhd9qroc-mysql.services.clever-cloud.com
      # DB_PORT: 3306
      # DB_USER: uvolnsnwvlmknr9f
      # DB_PASS: oPCjREhW0iVFnXu9b6JK
      # DB_DIALECT: mysql
      # NODE_ENV: production
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - movie_api_network
  nginx:
    build: ./nginx
    ports:
      - '3000:80'
    depends_on:
      - backend
networks:
  movie_api_network:
    driver: bridge
